spring.application.name=tarea3

# Las credenciales NO van escritas en el repo: se leen de variables de entorno.
spring.datasource.url=jdbc:postgresql://ep-odd-frog-b5tzbpjc-pooler.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_8pBKHZ0iujIA
spring.datasource.driver-class-name=org.postgresql.Driver
 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
 