### Registrar pedido
POST https://effective-journey-97w6pvjq7q99hpxp5-8080.app.github.dev/pedido/nuevo
Content-Type: application/json

{
 "items":[
   {
     "idProducto": 1004,
     "cantidad": 2,
     "precioUnitario":3000
   },
   {
     "idProducto": 1005,
     "cantidad": 3,
     "precioUnitario":50
   }
 ]
}